#!/usr/bin/env bash
set -euo pipefail

# Simple driver to build with Conan 2 for Android arm64-v8a using the
# preinstalled SDK/NDK at /opt/android-sdk and Qt outside Conan if needed.

PROJECT_DIR="$(cd "$(dirname "$0")" && pwd)"
BUILD_DIR="${PROJECT_DIR}/build/android-armv8"

mkdir -p "${BUILD_DIR}"

# Propagate proxy settings to Gradle if available (helps androiddeployqt wrapper)
if [ -n "${HTTPS_URL:-}" ] && [ -n "${HTTPS_PORT:-}" ]; then
  export JAVA_TOOL_OPTIONS="-Dhttps.proxyHost=${HTTPS_URL} -Dhttps.proxyPort=${HTTPS_PORT} ${JAVA_TOOL_OPTIONS:-}"
  export GRADLE_OPTS="-Dhttps.proxyHost=${HTTPS_URL} -Dhttps.proxyPort=${HTTPS_PORT} ${GRADLE_OPTS:-}"
fi
# If only standard HTTPS_PROXY provided, try to parse host:port
if [ -z "${HTTPS_URL:-}" ] && [ -n "${HTTPS_PROXY:-}" ]; then
  proto_host_port=$(printf '%s' "$HTTPS_PROXY" | sed -E 's#^([^:]+)://##')
  # Strip credentials if present
  host_port=$(printf '%s' "$proto_host_port" | sed -E 's#^[^@]+@##')
  hp_host=$(printf '%s' "$host_port" | cut -d':' -f1)
  hp_port=$(printf '%s' "$host_port" | cut -d':' -f2 | sed 's#/.*$##')
  if [ -n "$hp_host" ] && [ -n "$hp_port" ]; then
    export JAVA_TOOL_OPTIONS="-Dhttps.proxyHost=${hp_host} -Dhttps.proxyPort=${hp_port} ${JAVA_TOOL_OPTIONS:-}"
    export GRADLE_OPTS="-Dhttps.proxyHost=${hp_host} -Dhttps.proxyPort=${hp_port} ${GRADLE_OPTS:-}"
  fi
fi

# 1) Detect (or create) a native build profile once, outside of CI.
#    In container, you can run: conan profile detect --force
BUILD_PROFILE="${BUILD_PROFILE:-default}"
HOST_PROFILE="${PROJECT_DIR}/profiles/host-android-armv8"

# 2) Ensure a build profile exists (Conan 2) and install dependencies
#    In fresh containers there is no 'default' profile yet.
if ! conan profile list | awk '{print $1}' | grep -qx "${BUILD_PROFILE}"; then
  echo "[build.sh] Conan build profile '${BUILD_PROFILE}' not found; detecting default profile..." >&2
  conan profile detect --force
fi

# Install dependencies and generate toolchain files
conan install "${PROJECT_DIR}" \
  --profile:build="${BUILD_PROFILE}" \
  --profile:host="${HOST_PROFILE}" \
  -c tools.build:skip_test=True \
  -of "${BUILD_DIR}" -b missing

#!/usr/bin/env bash
EXTRA_ARGS=()

# Require Poppler sysroot (Mandatory)
DEFAULT_POPPLER_SYSROOT="${PROJECT_DIR}/../poppler-android-sysroot"
if [ -z "${SPEEDYNOTE_POPPLER_SYSROOT:-}" ]; then
  if [ -d "${DEFAULT_POPPLER_SYSROOT}" ]; then
    SPEEDYNOTE_POPPLER_SYSROOT="${DEFAULT_POPPLER_SYSROOT}"
  else
    echo "[build.sh] ERROR: Poppler sysroot required. Set SPEEDYNOTE_POPPLER_SYSROOT to an Android/arm64 Poppler install prefix (with pkgconfig)." >&2
    echo "           Suggested location: ${DEFAULT_POPPLER_SYSROOT}" >&2
    exit 2
  fi
fi

# Export pkg-config search path for Poppler and deps
export PKG_CONFIG_LIBDIR="${SPEEDYNOTE_POPPLER_SYSROOT}/lib/pkgconfig:${SPEEDYNOTE_POPPLER_SYSROOT}/share/pkgconfig${PKG_CONFIG_LIBDIR:+:${PKG_CONFIG_LIBDIR}}"
EXTRA_ARGS+=(
  -D SPEEDYNOTE_ENABLE_POPPLER=ON
  -D SPEEDYNOTE_POPPLER_SYSROOT="${SPEEDYNOTE_POPPLER_SYSROOT}"
)

# 3) Configure via CMake preset generated by CMakeToolchain
#    Pass Qt and Android locations so that find_package(Qt6 ...) resolves.
cmake --preset conan-debug \
  -D CMAKE_PREFIX_PATH=/opt/qt6-android-arm64 \
  -D QT_HOST_PATH=/opt/qt6-install \
  -D ANDROID_SDK_ROOT=/opt/android-sdk \
  -D ANDROID_NDK_ROOT=/opt/android-sdk/ndk/25.2.9519653 \
  ${EXTRA_ARGS[@]:-} \
  ${EXTRA_CMAKE_ARGS:-}

#!/usr/bin/env bash
# 4) Build (use preset build dir from the preset file)
cmake --build --preset conan-debug --parallel

# 5) Build APK (Qt will generate an 'apk' target that runs androiddeployqt)
if ! cmake --build --preset conan-debug --target apk --parallel; then
  # Fallback to target-specific packaging names used by Qt
  cmake --build --preset conan-debug --target QtHello_make_apk --parallel || true
  cmake --build --preset conan-debug --target NoteApp_make_apk --parallel || true
fi

# 6) Where deps and toolchain live (per Conan's cmake_layout)
echo "Conan output folder: ${BUILD_DIR}/build/Debug"
