#!/usr/bin/env bash
set -euo pipefail

# Simple driver to build with Conan 2 for Android arm64-v8a using the
# preinstalled SDK/NDK at /opt/android-sdk and Qt outside Conan if needed.

PROJECT_DIR="$(cd "$(dirname "$0")" && pwd)"
BUILD_DIR="${PROJECT_DIR}/build/android-armv8"

mkdir -p "${BUILD_DIR}"

# 1) Detect (or create) a native build profile once, outside of CI.
#    In container, you can run: conan profile detect --force
BUILD_PROFILE="${BUILD_PROFILE:-default}"
HOST_PROFILE="${PROJECT_DIR}/profiles/host-android-armv8"

# 2) Ensure a build profile exists (Conan 2) and install dependencies
#    In fresh containers there is no 'default' profile yet.
if ! conan profile list | awk '{print $1}' | grep -qx "${BUILD_PROFILE}"; then
  echo "[build.sh] Conan build profile '${BUILD_PROFILE}' not found; detecting default profile..." >&2
  conan profile detect --force
fi

# Install dependencies and generate toolchain files
conan install "${PROJECT_DIR}" \
  --profile:build="${BUILD_PROFILE}" \
  --profile:host="${HOST_PROFILE}" \
  -c tools.build:skip_test=True \
  -of "${BUILD_DIR}" -b missing

#!/usr/bin/env bash
# 3) Configure via CMake preset generated by CMakeToolchain
#    Pass Qt locations so that find_package(Qt6 ...) resolves to the preinstalled Qt.
cmake --preset conan-debug \
  -D CMAKE_PREFIX_PATH=/opt/qt6-android-arm64 \
  -D QT_HOST_PATH=/opt/qt6-install \
  -D ANDROID_SDK_ROOT=/opt/android-sdk \
  -D ANDROID_NDK_ROOT=/opt/android-sdk/ndk/25.2.9519653 \
  ${EXTRA_CMAKE_ARGS:-}

#!/usr/bin/env bash
# 4) Build (use preset build dir from the preset file)
cmake --build --preset conan-debug --parallel

# 5) Build APK (Qt will generate an 'apk' target that runs androiddeployqt)
if ! cmake --build --preset conan-debug --target apk --parallel; then
  # Fallback to target-specific packaging name used by Qt
  cmake --build --preset conan-debug --target QtHello_make_apk --parallel || true
fi

# 6) Where deps and toolchain live (per Conan's cmake_layout)
echo "Conan output folder: ${BUILD_DIR}/build/Debug"
